stages:
    - test

code-check:
    stage: test
    image: gitlab.mds.eu:2244/mds/docker-images/image-pimcore11-php82-webserver
    script:
        - echo "Executing mds-code-checker..."
        - cp -r $(pwd)/. /data
        - cd /data
        - composer install
        - vendor/bin/mds-code-check
