services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Mds\PimPrint\CoreBundle\Controller\:
        resource: '../src/Controller'
        public: true
        tags: ['controller.service_arguments']
        
    Mds\PimPrint\CoreBundle\Security\:
        resource: '../src/Security'

    Mds\PimPrint\CoreBundle\Service\:
        resource: '../src/Service'

    Mds\PimPrint\CoreBundle\Project\Interfaces\:
        resource: '../src/Project/Interfaces'

    # Special service configuration
    Mds\PimPrint\CoreBundle\Service\ProjectsManager:
        public: true
    Mds\PimPrint\CoreBundle\Service\UrlGeneratorAccessor:
        public: true

    #Bundle Installer
    Mds\PimPrint\CoreBundle\Tools\Installer:
        arguments:
            $bundle: "@=service('kernel').getBundle('MdsPimPrintCoreBundle')"
        public: true

    #Session
    mds.pimprint.session.configurator.mds_pimprint:
        class: Mds\PimPrint\CoreBundle\Session\PimPrintSessionBagConfigurator
        tags:
            - { name: pimcore.session.configurator }
